System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'x:\test-shoal-debugger\'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.VisualBasic.Shoal.Program.ScriptShellTerminal(Int32 ListenerPort, String work) in E:\SIYU_DNAuction\Shared Reference\Shoal\ShoalShell\ConsoleApplication\Program.vb:line 134
   at Microsoft.VisualBasic.Shoal.CommandLines.DEBUG(CommandLine argvs) in E:\SIYU_DNAuction\Shared Reference\Shoal\ShoalShell\ConsoleApplication\CommandLines.vb:line 134
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.VisualBasic.CommandLine.Reflection.EntryPoints.CommandEntryPointInfo.Invoke(Object[] parameters, Object target, Boolean Throw) in E:\SIYU_DNAuction\Shared Reference\Shoal\Microsoft.VisualBasic.Architecture.Framework\CommandLine\Reflection\EntryPoints\CommandEntryPointInfo.vb:line 139